train:
  ds_class: TranslationDataset
  ds_init_args:
    src_sp_model_file: data/multi30k/m_en_de.model
    tgt_sp_model_file: data/multi30k/m_en_de.model
    src_file: data/multi30k/train.de
    tgt_file: data/multi30k/train.en
    max_seq_len: 512
  dl_init_args:
    batch_size: 64
    shuffle: true
valid:
  ds_class: TranslationDataset
  ds_init_args:
    src_sp_model_file: data/multi30k/m_en_de.model
    tgt_sp_model_file: data/multi30k/m_en_de.model
    src_file: data/multi30k/val.de
    tgt_file: data/multi30k/val.en
    max_seq_len: 512
  dl_init_args:
    batch_size: 128
    shuffle: false