train:
  ds_class: TranslationDataset
  ds_init_args:
    src_sp_model_file: data/un/undoc.2000.fr-en.model
    tgt_sp_model_file: data/un/undoc.2000.fr-en.model
    src_file: data/un/undoc.2000.fr-en.en
    tgt_file: data/un/undoc.2000.fr-en.fr
    max_seq_len: 512
  dl_init_args:
    batch_size: 16 
    shuffle: true
valid:
  ds_class: TranslationDataset
  ds_init_args:
    src_sp_model_file: data/un/undoc.2000.fr-en.model
    tgt_sp_model_file: data/un/undoc.2000.fr-en.model
    src_file: data/news-commentary-v9/news-commentary-v9.fr-en.en
    tgt_file: data/news-commentary-v9/news-commentary-v9.fr-en.fr
    max_seq_len: 512
    first_n_lines: 10000
  dl_init_args:
    batch_size: 32
    shuffle: false
