max_steps: 5000 # 638 # ~ 50 epochs
val_check_interval: 100 # 1 epoch
check_val_every_n_epoch: null
accumulate_grad_batches: 4
log_every_n_steps: 10
gradient_clip_val: 10.0
model_checkpoint_interval: 100