train:
  ds_class: TranslationDatasetSpacy
  ds_init_args:
    split: train
    src_language: de
    tgt_language: en
  dl_init_args:
    batch_size: 256
    shuffle: true
valid:
  ds_class: TranslationDatasetSpacy
  ds_init_args:
    split: valid
    src_language: de
    tgt_language: en
  dl_init_args:
    batch_size: 256
    shuffle: false