learning_rate: 0.001
autotune_learning_rate: true
compile_model: false
shuffle: true
max_steps: 100000
batch_size: 128
gradient_accum_steps: 1
sp_model: data/multi30k/m_en_de.model
# training
train_src_file: data/multi30k/train.en
train_tgt_file: data/multi30k/train.de
# validation
val_src_file: data/multi30k/val.en
val_tgt_file: data/multi30k/val.de
